Satisfying Linter
bhsi-cinch/contentful-hugo pull request #8
Opened 2018-05-01 18:12 UTC by hyprhare

2018-05-02 12:51 UTC, icyitscold requested changes

2018-05-02 12:51 UTC, icyitscold commented on extract/extractor_test.go
> +			UsePreview:  "https://not.used.com" == "",
I think this should actually be a boolean - my bad for not changing that earlier. Surprised the linter is catching that

2018-05-03 20:12 UTC, hyprhare commented on extract/extractor_test.go
> +			UsePreview:  "https://not.used.com" == "",
Currently it IS a Boolean value which is evaluating as `false`.
Do you want it to be just a plain old `false` perhaps?

2018-05-04 12:57 UTC, icyitscold commented on extract/extractor_test.go
> +			UsePreview:  "https://not.used.com" == "",
Lol - missed that. Yes - superconfusing

2018-05-04 16:02 UTC, icyitscold approved these changes

2018-05-04 16:04 UTC, icyitscold approved these changes

2018-05-07 12:58 UTC, merged